// The aggregate projection (adopt-upstream #2): read every repo's trellis.json
// and generate the ORG describers — an org-map table + the contract lattice —
// from the same per-repo descriptors that generate each README. The org's maps
// stop drifting because they're derived, not hand-maintained. Bare nodes (a
// trellis node with no `descriptor` block yet) still appear, so the map is
// complete and the gaps are visible.
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";

const STATUS_BADGE: Record<string, string> = {
  Enforced: "🟢 Enforced",
  Partial: "🟡 Partial",
  Aspirational: "⚪ Aspirational",
};

// Lenient: unlike the strict TrellisNodeSchema, aggregate tolerates a bare node
// (provides/consumes but no descriptor) so un-adopted repos still show up.
const Contract = z.object({ type: z.string(), kind: z.string().optional() }).passthrough();
const LenientNode = z.object({
  node: z.string(),
  visibility: z.enum(["public", "private"]).optional(),
  provides: z.array(Contract).default([]),
  consumes: z.array(Contract).default([]),
  descriptor: z
    .object({
      tagline: z.string().optional(),
      role: z.object({ hotel: z.string(), kind: z.string() }).optional(),
      status: z.string().optional(),
    })
    .passthrough()
    .optional(),
});
export type AggNode = z.infer<typeof LenientNode>;

/** Read every trellis.json under a directory of repo checkouts (`<dir>/<repo>/trellis.json`). */
export function collectNodes(dir: string): AggNode[] {
  const nodes: AggNode[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = entry.isDirectory() ? join(dir, entry.name, "trellis.json") : entry.name === "trellis.json" ? join(dir, entry.name) : null;
    if (!p || !existsSync(p)) continue;
    const parsed = LenientNode.safeParse(JSON.parse(readFileSync(p, "utf8")));
    if (parsed.success) nodes.push(parsed.data);
  }
  return nodes.sort((a, b) => a.node.localeCompare(b.node));
}

const banner =
  "<!-- GENERATED by descriptor-kit (`descriptor aggregate`) from every repo's trellis.json. " +
  "The org map is derived from the per-repo descriptors, not hand-maintained — it can't drift. " +
  "Do not edit by hand. -->";

const repoLink = (n: AggNode) => `[\`${n.node}\`](https://github.com/bounded-systems/${n.node})`;

/** org-map.md — one row per node, drawn from its descriptor (bare nodes flagged). */
export function renderOrgMap(nodes: AggNode[]): string {
  const withDesc = nodes.filter((n) => n.descriptor?.tagline);
  const bare = nodes.filter((n) => !n.descriptor?.tagline);
  const lines: string[] = [
    "# bounded-systems — org map",
    "",
    banner,
    "",
    `**${nodes.length} nodes** — ${withDesc.length} with a descriptor, ${bare.length} bare (node declared, descriptor not yet authored).`,
    "",
    "| Repo | Role | Status | What it is |",
    "|---|---|---|---|",
  ];
  for (const n of withDesc) {
    const role = n.descriptor?.role ? `${n.descriptor.role.hotel} (${n.descriptor.role.kind})` : "—";
    const status = STATUS_BADGE[n.descriptor?.status ?? ""] ?? (n.descriptor?.status ?? "—");
    lines.push(`| ${repoLink(n)} | ${role} | ${status} | ${n.descriptor?.tagline} |`);
  }
  lines.push("");
  if (bare.length > 0) {
    lines.push("## Bare nodes (author a `descriptor` block to complete these)", "");
    for (const n of bare) lines.push(`- ${repoLink(n)} — provides ${n.provides.map((c) => `\`${c.type}\``).join(", ") || "—"}`);
    lines.push("");
  }
  return lines.join("\n");
}

/** The contract lattice — every provides→consumes edge, grouped by contract type. */
export function renderLattice(nodes: AggNode[]): string {
  const providers = new Map<string, string[]>();
  const consumers = new Map<string, string[]>();
  for (const n of nodes) {
    for (const p of n.provides) (providers.get(p.type) ?? providers.set(p.type, []).get(p.type)!).push(n.node);
    for (const c of n.consumes) (consumers.get(c.type) ?? consumers.set(c.type, []).get(c.type)!).push(n.node);
  }
  const types = [...new Set([...providers.keys(), ...consumers.keys()])].sort();
  const lines: string[] = ["# bounded-systems — contract lattice", "", banner, "", "| Contract type | Provided by | Consumed by |", "|---|---|---|"];
  for (const t of types) {
    const prov = (providers.get(t) ?? []).map((r) => `\`${r}\``).join(", ") || "— **unprovided**";
    const cons = (consumers.get(t) ?? []).map((r) => `\`${r}\``).join(", ") || "—";
    lines.push(`| \`${t}\` | ${prov} | ${cons} |`);
  }
  lines.push("");
  return lines.join("\n");
}
