// The value-prop model, matching prx's: a claim is BACKED only when each of its
// forcing functions holds *right now* — a live pure `check`, or external
// `evidence`. A `pending` forcing function is a learning goal, not a value prop.
// descriptor-kit imports a repo's value-props module, EXECUTES the checks, and
// renders docs/value-props.md + STATUS.md — so a claim cannot overclaim.

export type ForcingFunction =
  | { readonly name: string; readonly check: () => boolean; readonly exercises: readonly string[] }
  | { readonly name: string; readonly evidence: string; readonly exercises: readonly string[] }
  | { readonly name: string; readonly pending: string };

export interface ValueProp {
  readonly claim: string;
  readonly whyNot: string;
  readonly forcing: readonly ForcingFunction[];
}

export type FFState = "backed" | "evidence" | "pending";

export function ffState(f: ForcingFunction): FFState {
  if ("pending" in f) return "pending";
  if ("evidence" in f) return "evidence";
  return f.check() ? "backed" : "pending"; // a failing live check is not backed
}

export function propState(p: ValueProp): { backed: boolean; hasEvidence: boolean; learning: number } {
  const states = p.forcing.map(ffState);
  return {
    backed: states.every((s) => s === "backed" || s === "evidence"),
    hasEvidence: states.some((s) => s === "evidence"),
    learning: states.filter((s) => s === "pending").length,
  };
}

const GEN = (by: string) =>
  `<!-- GENERATED by descriptor-kit (${by}) by EXECUTING the forcing-function checks. A claim is BACKED only if its checks pass right now — it cannot overclaim. Do not edit by hand. -->`;

/** docs/value-props.md — the per-prop detail with the code→value-prop map. */
export function renderValueProps(props: readonly ValueProp[], node: string): string {
  const out: string[] = [
    `# ${node} — value props (forcing-function-backed)`,
    ``,
    GEN("value-props"),
    ``,
    `Each claim is **backed** only when its forcing functions hold now (a passing pure`,
    `check, or external evidence). A forcing function marked *learning goal* is not yet a`,
    `value prop. \`exercises\` is the code that delivers the claim.`,
    ``,
  ];
  for (const p of props) {
    const { backed } = propState(p);
    out.push(`## ${p.claim}  — ${backed ? "BACKED" : "NOT BACKED"}`, ``, `**Why not X:** ${p.whyNot}`, ``);
    for (const f of p.forcing) {
      const s = ffState(f);
      if (s === "pending" && "pending" in f) {
        out.push(`- [learning goal] ${f.name} — ${f.pending}`);
      } else if (s === "evidence" && "evidence" in f) {
        out.push(`- [evidence] ${f.name} — ${f.evidence}`, `  - exercises: ${f.exercises.join(", ")}`);
      } else if ("exercises" in f) {
        out.push(`- [${s}] ${f.name}`, `  - exercises: ${f.exercises.join(", ")}`);
      }
    }
    out.push(``);
  }
  return out.join("\n").trimEnd() + "\n";
}

/** STATUS.md — the rollup: N of M backed, what it does today, learning goals. */
export function renderStatus(props: readonly ValueProp[], node: string): string {
  const states = props.map((p) => ({ p, ...propState(p) }));
  const backed = states.filter((s) => s.backed);
  const liveBacked = backed.filter((s) => !s.hasEvidence);
  const evidence = backed.filter((s) => s.hasEvidence);
  const learning = states.flatMap((s) => s.p.forcing.filter((f) => "pending" in f));
  const out: string[] = [
    `# ${node} — status`,
    ``,
    GEN("status"),
    ``,
    `**${liveBacked.length} of ${props.length} value props fully backed** · ${evidence.length} evidence-backed (merged PR / recorded run, not a live check) · ${learning.length} learning goals.`,
    ``,
    `## What it does today`,
    ``,
  ];
  for (const s of backed) {
    out.push(`- ${s.p.claim}${s.hasEvidence ? " _(evidence-backed)_" : ""}`, `  - ${s.p.whyNot}`);
  }
  out.push(``, `## Learning goals (what's next)`, ``);
  if (learning.length === 0) out.push(`_(none)_`);
  else for (const f of learning) if ("pending" in f) out.push(`- ${f.name} — ${f.pending}`);
  return out.join("\n").trimEnd() + "\n";
}

/** Dynamically import a repo's value-props module and return its VALUE_PROPS export. */
export async function loadValueProps(absModulePath: string): Promise<readonly ValueProp[]> {
  const mod = await import(absModulePath);
  const vp = mod.VALUE_PROPS ?? mod.default;
  if (!Array.isArray(vp)) throw new Error(`value-props module has no VALUE_PROPS export: ${absModulePath}`);
  return vp as readonly ValueProp[];
}
