// The value-prop model, matching prx's exactly (this is prx's own generator,
// generalized over the repo name): a claim is BACKED only when each forcing
// function holds *right now* — a live pure `check`, or external `evidence`. A
// `pending` forcing function is a learning goal, not a value prop. descriptor-kit
// imports a repo's value-props module, EXECUTES the checks, and generates
// docs/value-props.md + STATUS.md — so a claim cannot overclaim.

export type ForcingFunction =
  | { readonly name: string; readonly check: () => boolean; readonly exercises: readonly string[] }
  | { readonly name: string; readonly evidence: string; readonly exercises: readonly string[] }
  | { readonly name: string; readonly pending: string };

export interface ValueProp {
  readonly claim: string;
  readonly whyNot: string;
  readonly forcing: readonly ForcingFunction[];
}

export type Backing = "backed" | "evidence" | "learning-goal";

export function backingOf(f: ForcingFunction): Backing {
  if ("check" in f) return f.check() ? "backed" : "learning-goal";
  if ("evidence" in f) return "evidence";
  return "learning-goal";
}

/** A value prop is backed iff none of its forcing functions are learning goals. */
export function isValuePropBacked(vp: ValueProp): boolean {
  return vp.forcing.every((f) => backingOf(f) !== "learning-goal");
}

/** Fully backed = every FF is a live pure check that passes right now (no evidence items). */
export function isFullyBacked(vp: ValueProp): boolean {
  return vp.forcing.every((f) => "check" in f && f.check());
}

/** Evidence-backed = backed (no learning goals) but at least one FF is evidence, not a live check. */
export function isEvidenceBacked(vp: ValueProp): boolean {
  return isValuePropBacked(vp) && !isFullyBacked(vp);
}

function exercisedBy(f: ForcingFunction): readonly string[] {
  return "exercises" in f ? f.exercises : [];
}

/** Reverse map: code symbol → the value-prop claims it delivers (pruning/refactoring lens). */
function codeToValueProps(props: readonly ValueProp[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const vp of props) {
    for (const f of vp.forcing) {
      for (const sym of exercisedBy(f)) {
        const arr = map.get(sym) ?? [];
        if (!arr.includes(vp.claim)) arr.push(vp.claim);
        map.set(sym, arr);
      }
    }
  }
  return map;
}

const banner = (kind: string) =>
  `<!-- GENERATED by descriptor-kit (\`descriptor render\`) by EXECUTING the ` +
  `forcing-function checks in the repo's value-props module. A claim is BACKED only if its ` +
  `checks pass right now — it cannot overclaim. Drift-checked by \`descriptor check\` in CI. ` +
  `Do not edit by hand. (${kind}) -->`;

function forcingLine(f: ForcingFunction): string {
  const backing = backingOf(f);
  const mark = backing === "backed" ? "[backed]" : backing === "evidence" ? "[evidence]" : "[learning goal]";
  const tail = "evidence" in f ? ` — ${f.evidence}` : "pending" in f ? ` — learning goal: ${f.pending}` : "";
  const exercises = "exercises" in f && f.exercises.length > 0 ? `\n  - exercises: ${f.exercises.join(", ")}` : "";
  return `- ${mark} ${f.name}${tail}${exercises}`;
}

/** docs/value-props.md — per-prop detail + the code→value-prop reverse map. */
export function renderValueProps(props: readonly ValueProp[], node: string): string {
  const lines: string[] = [
    `# ${node} — value props (forcing-function-backed)`,
    "",
    banner("value-props"),
    "",
    "Each claim is **backed** only when its forcing functions hold now (a passing pure",
    "check, or external evidence). A forcing function marked *learning goal* is not yet a",
    "value prop. `exercises` is the code that delivers the claim — the refactoring contract",
    "(keep it green) and the pruning lens (code that traces to nothing is a prune candidate).",
    "",
  ];
  for (const vp of props) {
    lines.push(`## ${vp.claim}  — ${isValuePropBacked(vp) ? "BACKED" : "LEARNING GOAL"}`, "");
    lines.push(`**Why not X:** ${vp.whyNot}`, "");
    for (const f of vp.forcing) lines.push(forcingLine(f));
    lines.push("");
  }
  lines.push("## Code → value props (pruning / refactoring lens)", "");
  const reverse = [...codeToValueProps(props).entries()].sort(([a], [b]) => a.localeCompare(b));
  for (const [sym, claims] of reverse) lines.push(`- \`${sym}\` → ${claims.map((c) => `"${c}"`).join("; ")}`);
  lines.push("");
  return lines.join("\n");
}

/** STATUS.md — the rollup: N of M backed, what it does today, learning goals. */
export function renderStatus(props: readonly ValueProp[], node: string): string {
  const fullyBacked = props.filter(isFullyBacked);
  const evidenceBacked = props.filter(isEvidenceBacked);
  const learning = props.filter((vp) => !isValuePropBacked(vp));
  const evidenceNote =
    evidenceBacked.length > 0
      ? ` · ${evidenceBacked.length} evidence-backed (merged PR / recorded run, not a live check)`
      : "";
  const lines: string[] = [
    `# ${node} — status`,
    "",
    banner("status"),
    "",
    `**${fullyBacked.length} of ${props.length} value props fully backed**${evidenceNote} · ${learning.length} learning goal${learning.length === 1 ? "" : "s"}.`,
    "",
    `## What ${node} does today`,
    "",
  ];
  const allBacked = props.filter(isValuePropBacked);
  if (allBacked.length === 0) lines.push("_(none backed yet)_");
  for (const vp of allBacked) {
    lines.push(`- ${vp.claim}${isFullyBacked(vp) ? "" : " _(evidence-backed)_"}`);
    lines.push(`  - ${vp.whyNot}`);
  }
  lines.push("", "## Learning goals (what's next)", "");
  if (learning.length === 0) lines.push("_(none)_");
  for (const vp of learning) {
    lines.push(`- ${vp.claim}`);
    for (const f of vp.forcing) if (backingOf(f) === "learning-goal") lines.push(`  - ${"pending" in f ? f.pending : f.name}`);
  }
  lines.push("", "_See [docs/value-props.md](docs/value-props.md) for the forcing functions + the code→value-prop map._", "");
  return lines.join("\n");
}

/** Dynamically import a repo's value-props module and return its VALUE_PROPS export. */
export async function loadValueProps(absModulePath: string): Promise<readonly ValueProp[]> {
  const mod = await import(absModulePath);
  const vp = mod.VALUE_PROPS ?? mod.default;
  if (!Array.isArray(vp)) throw new Error(`value-props module has no VALUE_PROPS export: ${absModulePath}`);
  return vp as readonly ValueProp[];
}
